Repository ISIS3510-202410-Team11/Swift, pull requests merged in 2024-05, with the labels that each got.

#48 added connectivity app manager and validations on each button of profile view
  RideShare.xcodeproj/project.pbxproj
  RideShare/ContentView.swift
  RideShare/FirestoreManager.swift
  RideShare/RideShareApp.swift
  RideShare/Utilities/ConnectivityManager.swift
  RideShare/Utilities/Tabvar.swift
  RideShare/ViewModels/ProfileViewModel.swift
  RideShare/Views/ConnectivityBanner.swift
  RideShare/Views/OverlayConnectivityBanner.swift
  RideShare/Views/Profile/ProfileView.swift
  RideShare/Views/Registration/NewCarView.swift
Labels: enhancement

#50 Solve syntax problem
  RideShare.xcodeproj/project.xcworkspace/xcuserdata/cristiancaro11.xcuserdatad/UserInterfaceState.xcuserstate
  RideShare/FirestoreManager.swift
  RideShare/RideShareApp.swift
  RideShare/ViewModels/Map/RidePickerViewModel.swift
  RideShare/Views/Map/ClickService.swift
  RideShare/Views/Map/RidePickerView.swift
Labels: enhancement, good first issue

#51 Feature/create ride
  RideShare.xcodeproj/project.pbxproj
  RideShare.xcodeproj/xcuserdata/pabluchenko.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RideShare/FirestoreManager.swift
  RideShare/Models/MapViewState.swift
  RideShare/Utilities/Cards.swift
  RideShare/Utilities/SessionManager.swift
  RideShare/Utilities/Tabvar.swift
  RideShare/ViewModels/Map/LocationSearchViewModel.swift
  RideShare/ViewModels/ProfileViewModel.swift
  RideShare/ViewModels/Registration/NewCarViewModel.swift
  RideShare/Views/Map/Driver/CreateRideView.swift
  RideShare/Views/Map/Driver/RiderInteractionView.swift
  RideShare/Views/Map/MapRepresentable.swift
  RideShare/Views/Map/MapView.swift
  RideShare/Views/Map/OptionsButtonView.swift
  RideShare/Views/Map/PaymentView.swift
  RideShare/Views/Map/RidePickerCell.swift
  RideShare/Views/Map/RideRequestView.swift
  RideShare/Views/Map/Rider/DriverInteractionView.swift
  RideShare/Views/Profile/ProfileView.swift
  RideShare/Views/ServicesView.swift
Labels: enhancement

#52 Revert "Feature/create ride"
  RideShare.xcodeproj/project.pbxproj
  RideShare.xcodeproj/xcuserdata/pabluchenko.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RideShare/FirestoreManager.swift
  RideShare/Models/MapViewState.swift
  RideShare/Utilities/Cards.swift
  RideShare/Utilities/SessionManager.swift
  RideShare/Utilities/Tabvar.swift
  RideShare/ViewModels/Map/LocationSearchViewModel.swift
  RideShare/ViewModels/ProfileViewModel.swift
  RideShare/ViewModels/Registration/NewCarViewModel.swift
  RideShare/Views/Map/Driver/CreateRideView.swift
  RideShare/Views/Map/Driver/RiderInteractionView.swift
  RideShare/Views/Map/MapRepresentable.swift
  RideShare/Views/Map/MapView.swift
  RideShare/Views/Map/OptionsButtonView.swift
  RideShare/Views/Map/PaymentView.swift
  RideShare/Views/Map/RidePickerCell.swift
  RideShare/Views/Map/RideRequestView.swift
  RideShare/Views/Map/Rider/DriverInteractionView.swift
  RideShare/Views/Profile/ProfileView.swift
  RideShare/Views/ServicesView.swift
Labels: bug

#54 implementedPickedLocationForDriver
  RideShare.xcodeproj/project.pbxproj
  RideShare/ViewModels/Map/CreateRideViewModel.swift
  RideShare/Views/Map/Driver/CreateRideView.swift
  RideShare/Views/Map/LocationSearchView.swift
  RideShare/Views/Map/Rider/DriverInteractionView.swift
Labels: enhancement

#53 Feature/pipeline
  RideShare.xcodeproj/project.pbxproj
  RideShare.xcodeproj/project.xcworkspace/xcuserdata/cristiancaro11.xcuserdatad/UserInterfaceState.xcuserstate
  RideShare.xcodeproj/xcshareddata/xcschemes/RideShare.xcscheme
  RideShare.xcodeproj/xcuserdata/cristiancaro11.xcuserdatad/xcschemes/xcschememanagement.plist
  RideShare/Models/MapViewState.swift
  RideShare/RideShareApp.swift
  RideShare/ViewModels/Map/AnalyticsManager.swift
  RideShare/ViewModels/Map/PQRViewModel.swift
  RideShare/Views/Map/LocationDetail.swift
  RideShare/Views/Map/LocationSearchView.swift
  RideShare/Views/Map/OptionsButtonView.swift
  RideShare/Views/Map/PQRView.swift
  RideShare/Views/Map/PaymentView.swift
  RideShare/Views/Map/RideRequestView.swift
  RideShare/Views/Profile/ProfileView.swift
  RideShare/Views/Registration/ForgotPasswordView.swift
  RideShare/Views/Registration/LoginView.swift
  RideShare/Views/Registration/RegistrationView.swift
  RideShare/Views/Registration/SignUpView.swift
  RideShare/Views/SpeedView.swift
Labels: enhancement

#57 Enhancement/create ride
  RideShare.xcodeproj/project.pbxproj
  RideShare/FirestoreManager.swift
  RideShare/Models/MapViewState.swift
  RideShare/Models/Passenger.swift
  RideShare/RideShareApp.swift
  RideShare/ViewModels/Map/CreateRideViewModel.swift
  RideShare/ViewModels/RideStatusViewModel.swift
  RideShare/Views/Map/Driver/CreateRideView.swift
  RideShare/Views/Map/Driver/DriverInteractionView.swift
  RideShare/Views/Map/Driver/RideStatusView.swift
  RideShare/Views/Map/DropDownMenuView.swift
  RideShare/Views/Map/LocationDetail.swift
  RideShare/Views/Map/MapRepresentable.swift
  RideShare/Views/Map/MapView.swift
  RideShare/Views/Map/OptionsButtonView.swift
  RideShare/Views/Map/RideRequestView.swift
Labels: enhancement

#58 Feature/pq rs
  RideShare.xcodeproj/project.pbxproj
  RideShare.xcodeproj/project.xcworkspace/xcuserdata/cristiancaro11.xcuserdatad/UserInterfaceState.xcuserstate
  RideShare/Models/ActiveTrips.swift
  RideShare/Models/MapViewState.swift
  RideShare/Models/PQR.swift
  RideShare/ViewModels/Map/LocationSearchViewModel.swift
  RideShare/ViewModels/Map/PQRViewModel.swift
  RideShare/ViewModels/Map/PaymentViewModel.swift
  RideShare/ViewModels/Map/RidePickerViewModel.swift
  RideShare/Views/Map/MapRepresentable.swift
  RideShare/Views/Map/MapView.swift
  RideShare/Views/Map/OptionsButtonView.swift
  RideShare/Views/Map/PQRView.swift
  RideShare/Views/Map/PaymentView.swift
  RideShare/Views/Map/RidePickerCell.swift
  RideShare/Views/Map/RidePickerView.swift
Labels: enhancement
